//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ImdbEx2
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MyProjectsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MyProjectsEntities object using the connection string found in the 'MyProjectsEntities' section of the application configuration file.
        /// </summary>
        public MyProjectsEntities() : base("name=MyProjectsEntities", "MyProjectsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyProjectsEntities object.
        /// </summary>
        public MyProjectsEntities(string connectionString) : base(connectionString, "MyProjectsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyProjectsEntities object.
        /// </summary>
        public MyProjectsEntities(EntityConnection connection) : base(connection, "MyProjectsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Not_Flixster> tbl_Not_Flixster
        {
            get
            {
                if ((_tbl_Not_Flixster == null))
                {
                    _tbl_Not_Flixster = base.CreateObjectSet<tbl_Not_Flixster>("tbl_Not_Flixster");
                }
                return _tbl_Not_Flixster;
            }
        }
        private ObjectSet<tbl_Not_Flixster> _tbl_Not_Flixster;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Not_Flixster_Reviews> tbl_Not_Flixster_Reviews
        {
            get
            {
                if ((_tbl_Not_Flixster_Reviews == null))
                {
                    _tbl_Not_Flixster_Reviews = base.CreateObjectSet<tbl_Not_Flixster_Reviews>("tbl_Not_Flixster_Reviews");
                }
                return _tbl_Not_Flixster_Reviews;
            }
        }
        private ObjectSet<tbl_Not_Flixster_Reviews> _tbl_Not_Flixster_Reviews;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Not_Flixster EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Not_Flixster(tbl_Not_Flixster tbl_Not_Flixster)
        {
            base.AddObject("tbl_Not_Flixster", tbl_Not_Flixster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Not_Flixster_Reviews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Not_Flixster_Reviews(tbl_Not_Flixster_Reviews tbl_Not_Flixster_Reviews)
        {
            base.AddObject("tbl_Not_Flixster_Reviews", tbl_Not_Flixster_Reviews);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyProjectsModel", Name="tbl_Not_Flixster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Not_Flixster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Not_Flixster object.
        /// </summary>
        /// <param name="ourID">Initial value of the OurID property.</param>
        public static tbl_Not_Flixster Createtbl_Not_Flixster(global::System.Int32 ourID)
        {
            tbl_Not_Flixster tbl_Not_Flixster = new tbl_Not_Flixster();
            tbl_Not_Flixster.OurID = ourID;
            return tbl_Not_Flixster;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OurID
        {
            get
            {
                return _OurID;
            }
            set
            {
                if (_OurID != value)
                {
                    OnOurIDChanging(value);
                    ReportPropertyChanging("OurID");
                    _OurID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OurID");
                    OnOurIDChanged();
                }
            }
        }
        private global::System.Int32 _OurID;
        partial void OnOurIDChanging(global::System.Int32 value);
        partial void OnOurIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OurDesc
        {
            get
            {
                return _OurDesc;
            }
            set
            {
                OnOurDescChanging(value);
                ReportPropertyChanging("OurDesc");
                _OurDesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OurDesc");
                OnOurDescChanged();
            }
        }
        private global::System.String _OurDesc;
        partial void OnOurDescChanging(global::System.String value);
        partial void OnOurDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OurCountriesReleasedIn
        {
            get
            {
                return _OurCountriesReleasedIn;
            }
            set
            {
                OnOurCountriesReleasedInChanging(value);
                ReportPropertyChanging("OurCountriesReleasedIn");
                _OurCountriesReleasedIn = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OurCountriesReleasedIn");
                OnOurCountriesReleasedInChanged();
            }
        }
        private global::System.String _OurCountriesReleasedIn;
        partial void OnOurCountriesReleasedInChanging(global::System.String value);
        partial void OnOurCountriesReleasedInChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OurRating
        {
            get
            {
                return _OurRating;
            }
            set
            {
                OnOurRatingChanging(value);
                ReportPropertyChanging("OurRating");
                _OurRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OurRating");
                OnOurRatingChanged();
            }
        }
        private Nullable<global::System.Int32> _OurRating;
        partial void OnOurRatingChanging(Nullable<global::System.Int32> value);
        partial void OnOurRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OurTitle
        {
            get
            {
                return _OurTitle;
            }
            set
            {
                OnOurTitleChanging(value);
                ReportPropertyChanging("OurTitle");
                _OurTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OurTitle");
                OnOurTitleChanged();
            }
        }
        private global::System.String _OurTitle;
        partial void OnOurTitleChanging(global::System.String value);
        partial void OnOurTitleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyProjectsModel", Name="tbl_Not_Flixster_Reviews")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Not_Flixster_Reviews : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Not_Flixster_Reviews object.
        /// </summary>
        /// <param name="ourID">Initial value of the OurID property.</param>
        /// <param name="ourReviewID">Initial value of the OurReviewID property.</param>
        public static tbl_Not_Flixster_Reviews Createtbl_Not_Flixster_Reviews(global::System.Int32 ourID, global::System.Int32 ourReviewID)
        {
            tbl_Not_Flixster_Reviews tbl_Not_Flixster_Reviews = new tbl_Not_Flixster_Reviews();
            tbl_Not_Flixster_Reviews.OurID = ourID;
            tbl_Not_Flixster_Reviews.OurReviewID = ourReviewID;
            return tbl_Not_Flixster_Reviews;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OurID
        {
            get
            {
                return _OurID;
            }
            set
            {
                OnOurIDChanging(value);
                ReportPropertyChanging("OurID");
                _OurID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OurID");
                OnOurIDChanged();
            }
        }
        private global::System.Int32 _OurID;
        partial void OnOurIDChanging(global::System.Int32 value);
        partial void OnOurIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OurReviewID
        {
            get
            {
                return _OurReviewID;
            }
            set
            {
                if (_OurReviewID != value)
                {
                    OnOurReviewIDChanging(value);
                    ReportPropertyChanging("OurReviewID");
                    _OurReviewID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OurReviewID");
                    OnOurReviewIDChanged();
                }
            }
        }
        private global::System.Int32 _OurReviewID;
        partial void OnOurReviewIDChanging(global::System.Int32 value);
        partial void OnOurReviewIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OurReviews
        {
            get
            {
                return _OurReviews;
            }
            set
            {
                OnOurReviewsChanging(value);
                ReportPropertyChanging("OurReviews");
                _OurReviews = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OurReviews");
                OnOurReviewsChanged();
            }
        }
        private global::System.String _OurReviews;
        partial void OnOurReviewsChanging(global::System.String value);
        partial void OnOurReviewsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OurReviewsDaysAgo
        {
            get
            {
                return _OurReviewsDaysAgo;
            }
            set
            {
                OnOurReviewsDaysAgoChanging(value);
                ReportPropertyChanging("OurReviewsDaysAgo");
                _OurReviewsDaysAgo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OurReviewsDaysAgo");
                OnOurReviewsDaysAgoChanged();
            }
        }
        private Nullable<global::System.Int32> _OurReviewsDaysAgo;
        partial void OnOurReviewsDaysAgoChanging(Nullable<global::System.Int32> value);
        partial void OnOurReviewsDaysAgoChanged();

        #endregion
    
    }

    #endregion
    
}
